name: risa2
description: IT Pelindo III Regional Banjarmasin Tools.

publish_to: 'none'

version: 1.1.8+8

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.17
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  dio: 4.0.0-beta6
  firebase_analytics: ^8.1.2
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2
  fl_chart: ^0.36.1
  flutter_image_compress: ^1.0.0
  flutter_local_notifications: ^6.0.0
  flutter_speed_dial: ^3.0.5
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.20.0-nullsafety.3
  google_fonts: ^2.0.0
  http: any
  image_picker: ^0.7.4
  photo_view: ^0.12.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.0
  lottie: ^1.0.1
  meta: ^1.3.0-nullsafety.6
  page_transition: 2.0.1-nullsafety.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  shared_preferences: ^2.0.3
  url_launcher: ^6.0.7
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icon/icon.png
    - assets/lottie/629-empty-box.json
    - google_fonts/
